<?xml version="1.0"?>
<!DOCTYPE menuDesayunos [
        <!ELEMENT menuDesayunos (comida)*>
        <!ELEMENT comida (nombre, precio, descripcion, calorias)>
        <!ATTLIST comida id ID #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ATTLIST precio moneda CDATA #IMPLIED>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT calorias (#PCDATA)>
        ]>
<menuDesayunos>
    <comida id="GB">
        <nombre>Gofres Belgas</nombre>
        <precio>5.95</precio>
        <descripcion>
            Dos de nuestros famosos gofres belgas
            con abundante sirope
        </descripcion>
        <calorias>650</calorias>
    </comida>
    <comida id="GBF">
        <nombre>Gofres belgas con fresas</nombre>
        <precio>7.95</precio>
        <descripcion>
            Ligeros gofres belgas cubiertos de fresas y nata montada
        </descripcion>
        <calorias>900</calorias>
    </comida>
    <comida id="GBFB">
        <nombre>Gofres Belgas con frutas del bosque</nombre>
        <precio>8.95</precio>
        <descripcion>
            ligeros gofres belgas cubiertos con frutas
            del bosque y nata montada
        </descripcion>
        <calorias>900</calorias>
    </comida>
    <comida id="TF">
        <nombre>Tostada francesa</nombre>
        <precio>4.50</precio>
        <descripcion>
           Dos gruyesas rebanadas de nuestro pan
            frances casero
        </descripcion>
        <calorias>600</calorias>
    </comida>
    <comida id="DC">
        <nombre>Desayuno de la casa</nombre>
        <precio>6.95</precio>
        <descripcion>
            Dos huevos, blancos o salchicha, tostada
            y patatas fritas
        </descripcion>
        <calorias>950</calorias>
    </comida>
</menuDesayunos>